### PR TITLE
Add columns for Caught Location

### LINKED ISSUE #423: Spawnpoint_id / pokestop_id ,  or at least city
The server seems to be sending some geo data of the capture... could it be possible to visualise it?

### PR DESCRIPTION
**Pull request by Wolfsblvt**
## Adds to columns to the table
- **Caught Coordinates**
- **Caught Location**
- **Caught City**

One displaying the coordinates (latitude, longitude) and other tow that shows the detailed location name and the city. Even more detailed than Niantic does in-app.

For that, I query the **Google Maps Geocoding API**. and analyzes the response.
The _problem_ is that Google has [some Usage Limits](https://developers.google.com/maps/documentation/geocoding/usage-limits) for their API, which is understandable. So we can only query 50 locations at once, and 2.5k total per day.
To work around that problem I implemented caching, so that every location that was queried already is saved in runtime, and also in `locations.json` file. That's even cooler cause same-spawn-pokémon have the exact same location. So that's not queried again.

Do note that when the locations are queried the first time, it will surely hit the 50 locations limit. User has to refresh some times until he has all location data saved locally.

**Note:** The Locations are language specific. That means the users selected language for this tool will be used to query the API. The data will be cached in that language.
But that does also mean that if the user changes his language, the cached data stays with the old language.
## ColumnType.FUTURE_STRING added

Added a column type for Futures. That means displaying data that needs some time to calculate or get. At first, a `... Loading ....` placeholder is displayed. When the data is ready, it is displayed.
Pretty cool, huh?

Resolves #423.

### CODE REVIEW

**Comment by Wolfsblvt** [comment]
Code checks are fine. We should ignore the `AccountController` errors, until someone takes over and reworks that class to match code style.
If I do that here, the changes would be huge.

**Comment by DrDragonKiller** [comment]
column of caught location is flickering (I send you a video in a discord DM)

**Comment by Wolfsblvt** [comment]
Fixed the flickering now by caching the Future's values inside the FutureCellRenderer. Not very beautiful, but it works. Also improves speed of loading that values again.

I also made the queried locations language-specific.

PR is finished now and can be reviewed.

**Comment by Wolfsblvt** [comment]
There is no reviews, but changes need to be merged. Okay, fine.

**Pull request merged**
