### PR TITLE
Creating new patterns about ISSUE #301

### PR DESCRIPTION
**Pull request by FernandoTBarros**
Created new patterns for renaming IV atk, def, stam and move types and pokemon types using unicode characters.

### CODE REVIEW

**Comment by Wolfsblvt** [comment]
Codacy formatting errors should be fixed.
Ignore the codeclimate error with "BUG" xD

EDIT://
If you are finished editing, just write a short comment here, then I can change labels.

**Comment by FernandoTBarros** [comment]
Hahaha Impossible BUG fix LOL
Codacy is complaining about indentation, but in my code it's in correct position. What's happening?

**Comment by Wolfsblvt** [comment]
You should set up intendation correctly in your IDE.
You should never use tabs. And for intendation we use four spaces. That's your way to go.

**Comment by FernandoTBarros** [comment]
Ok. I'm done! ;)

**Comment by Wolfsblvt** [comment]
Seems fine for me. Small things like that empty string without warning if the pattern is not found is maybe not ideally, but can be done later.

**Pull request merged**
