### PR TITLE
Added a visual feature to show evolvable Pokémons

### PR DESCRIPTION
**Pull request by LivioGama**
Added a visual feature to show evolvable Pokémons

### CODE REVIEW

**Comment by LivioGama** [comment]
capture d ecran 2016-08-21 a 21 34 21

**Comment by LivioGama** [comment]
Actually, don't merge it immediately, there are some bugs : sometimes the toggling has some glitch and not all the cells have their background changed. And worse : cell selection doesn't work anymore, I think I need to use the setDefaultSelectionColors method that I will refactor.

**Comment by LivioGama** [comment]
Ok I fixed the selection. But for the glitch, I might need your help :$ I have no experience in Java window app, maybe you'll see immediately the problem

**Comment by LivioGama** [comment]
Also the font size changing doesn't work, I don't know how to manage it

**Comment by Wolfsblvt** [comment]
Labeled the Pull Request correct now. Will look into it soon, maybe I'll find the issue for your problem :D

**Comment by ritsu** [comment]
Regarding the font size issue, font size is currently only applied to the default PokemonTable cell renderer. So, any custom object that implements TableCellRenderer will have to call setFont() to set the appropriate font at startup, and the font dropdown ActionListener will have to be updated to call setFont() on all the TableCellRenderer objects as well.

FYI, this is also currently the case with MoveSetRankingRenderer. 

One issue is in order to grab font size from the config file in a static TableCellRenderer, you'll have to declare the ConfigNew object static. And if you want to call getFont() on the PokemonTable object, then that has to be declared static as well.

Edit: I can submit a fix for the MoveSetRankingRenderer font issue if you think it's necessary with the JavaFX release on the horizon.

**Comment by Ljaysoft** [comment]
needs merging

**Comment by Wolfsblvt** [comment]
This PR is long dead. Think we will find another way to add Evolvable Highlighting, if needed.

**Pull request closed without merging**
