### PR TITLE
Implement 'Do not show bulk finishes window'

### PR DESCRIPTION
**Pull request by Cryptically**
Done Issue #223 on hiding bulk popup message.

Persisted transfer after evolve.
Created settings menu.

### CODE REVIEW

**Comment by Wolfsblvt** [comment]
Nice thing. Guess I'll rework that a bit still though.
Don't like the many if blocks if not needed.

Today or tomorrow (:

**Comment by Cryptically** [comment]
I guess un-nesting all the if with returns would do good.
And the transfer, rename, power up, evolve methods are pretty long too.

**Comment by Wolfsblvt** [comment]
They will be refactored sometime in the future. Hopefully. Where the UI logic is split apart from the general routine.
But as long as it works it's not the most important thing to do.

**Comment by Wolfsblvt** [comment]
My PR is out. Do not change this PR here. It will be automatically merged when mine is accepted.
You can take a look at it there, @Cryptically (:
If that's okay for you there I mean.

**Comment by Cryptically** [comment]
Yeah, no problem

**Pull request merged**
