### PR TITLE
Added contributors to about.

### LINKED ISSUE #57: Add collaborator names in Help window
Heya guys. @Blossomforth said that he wanted to add us as collaborators in the "Help" window and such.
Would just do that, but I guess it would be fair to ask everyone if he wants to be named there, and what name exactly should be written there. Some want GitHub usenames, others real names, etc.

Pinging @wullxz , @Ljaysoft , @weblue and @Wolfsblvt .

### PR DESCRIPTION
**Pull request by andyzen619**
Fixes #57

### CODE REVIEW

**Comment by andyzen619** [comment]
Added the contributors taken directly from the contributors list.  I am kind of new to open source so any advice would be appreciated.

**Comment by Wolfsblvt** [comment]
Seems okay to me.

We should just keep an eye on it then and update the list every now and then.

**Comment by Wolfsblvt** [comment]
Okay fuck, same error again and I haven't even seen it xD
We do each pill request against `develop`, not master.
Do please create a new PR against the correct branch.

I'll revert the current merge.

**Comment by andyzen619** [comment]
Done #238

**Pull request merged**
