### PR TITLE
Fixes Window Title Update on Refresh List #518

### PR DESCRIPTION
**Pull request by Kati3e**
Fixes issue "Window Title does not update on "Refresh List" #518

### CODE REVIEW

**Review by Wolfsblvt — APPROVED** [review]
Yep, that works.

**Comment by Wolfsblvt** [comment]
Thank you for that quick fix (:

**Comment by Kati3e** [comment]
No problem! I love this tool. I am so glad and thankful you are keeping it alive for us, I'd like to help out more wherever I can, unfortunately I don't have a lot of time to really dive into the code to help with bigger things, but I hope I can soon!

**Comment by Wolfsblvt** [comment]
No worries, small things are fine too (:
Every help is appreciated.

**Pull request merged**
