### PR TITLE
Allow users to set their own DeviceInfo settings

### PR DESCRIPTION
**Pull request by FernandoTBarros**
Creating CustomDeviceInfo class to allow user set their own DeviceInfo settings that will be passed to API.
The config is through config.json file for now.
To get your config in Android I recommend the simple Build Info app (https://play.google.com/store/apps/details?id=omorapps.build_info). 
On iOS I need help on this task =)

### CODE REVIEW

**Comment by Wolfsblvt** [comment]
What help do you need for iOS?

Hmh, I guess we have to clear up a few things. As far as I understood, the PokeGOAPI uses a default device info if none is specified, yes?
Ar those the device infos you've chosen as default values on the keys?
And do we always send a custom device info now? If so, I guess I would like it more if you would make a switch configKey with default false (like you already have, just comment it in), and wrap those device infos in an if block. That way our info wouldn't get outdated, and for people that haven't changed the config.json to have a matching deviceInfo it just uses the APIs default, no matter what's in our default keys.

**Comment by FernandoTBarros** [comment]
An app to view the deviceInfo for iOS. 

Yes, those default values I choose is the ones I get from DeviceInfo used on PokeGOAPI.
Yes, I agree with you. Gonna make this way.

**Comment by Wolfsblvt** [comment]
Needs merge conflicts resolved.

Also, I will quote me on Discord:

> I am still unsure if we should add the deviceInfo nodes to the config.json by default. I am not a huge fan of cluttered config.jsons with so many data in it which a normal user can't even understand.
> 
> You have done well to choose deviceInfo.custom as sub-node for device info.
> So what do you think about defaulting all those values to null, which will prevent them being added to the config.json by default, so we only have the deviceInfo.useCustom: false there.
> 
> And then you provide the JSON markup needed to enter a custom device info in your wiki page.
> The wiki page is already needed to understand what to do. So you could just enter the code there

That's the way we go now.

**Comment by FernandoTBarros** [comment]
Everything is done now.
Linking the [Wiki ](https://github.com/Wolfsblvt/BlossomsPokemonGoManager/wiki/Using-your-own-DeviceInfo-to-connect-to-API) here to documentation

**Comment by FernandoTBarros** [comment]
Wait to merge. Apparently that value!=null solution to ConfigNew broken something. Trying to figure out.
But my app doesn't start after I merge to your branch because of your new config values.

**Comment by FernandoTBarros** [comment]
Ok, I reverted the commit of ConfigNew file. All the logic of it's functions are based on that all nodes exists. 
So, in order to change what I changed, needs to refactor all the functions to treat non existent nodes.

**Review by Wolfsblvt — APPROVED** [review]
Fine, will merge now.

**Pull request merged**
