### PR TITLE
New pokemon table fill

### PR DESCRIPTION
**Pull request by Ljaysoft**
The table is now filled.
-Multisortable (with shift click on table column title)
-Saves the position of the columns
-Still problems with sorting some columns
-Rightclick context menu for operations with selection (only GUI side implemented)

### CODE REVIEW

**Comment by Ljaysoft** [comment]
I added a bunch of stuff, I updated the first post

**Comment by Ljaysoft** [comment]
this is what the UI looks like btw
login
mainwindow
context

**Comment by Ljaysoft** [comment]
Added a batch operation window, and added an Operation and OperationID class

**Comment by Cryptically** [comment]
Probably should merge this. This pr is getting bigger and bigger.

**Comment by Ljaysoft** [comment]
I was waiting on someone's approval, but @Wolfsblvt takes days to merge my PRs ;)

**Pull request merged**
