### PR TITLE
Stardust calculations bugfix

### PR DESCRIPTION
**Pull request by Purely-Imaginary**
My first pull request, covering this issue: https://github.com/Blossomforth/BlossomsPokemonGoManager/issues/164

### CODE REVIEW

**Comment by Wolfsblvt** [comment]
Reviewed it.
You know what the problem is? You really fixed the bug, but it doesn't help for our tool ._.
The formula written there is not used for that table value xD Even if we would try, it would need the number of powerUps done to that Pokémon, and that we don't have available and don't have a chance to get it - as far as I know.
What you did is finding a bug in the [PokeGOAPI](https://github.com/Grover-c13/PokeGOAPI-Java/) we use. It's calling their `.getStardustCostsForPowerup()` in the PokemonTab, you can look there.

So I guess we can't merge that here. Or better, we can, but it doesn't help. The bug needs to be fixed in their API.
Maybe you can do a Pull Request on their Repo? :P

**Comment by Purely-Imaginary** [comment]
That would explain everything! I thought that I've got problems on my side that I can't get my IntelliJ to run updated version of code :D I'll go and get it fixed on their side! Thanks for pointing where to go!

EDIT: I hope that is right, I couldn't make it run on my machine. [Link to PR](https://github.com/Grover-c13/PokeGOAPI-Java/pull/551)

**Comment by Purely-Imaginary** [comment]
Okay, they did it already before I got a chance, they will merge it in when Grover-c13 will have time.

**Comment by Wolfsblvt** [comment]
Okidoki. Then let's wait for the next API version (:

**Pull request closed without merging**
