### PR TITLE
poke evolves

### PR DESCRIPTION
**Pull request by nts64**
Small util I wrote to calculate my Lucky Egg evolves.
Hooked to refresh list button, prints the summary in the console

### CODE REVIEW

**Comment by Cryptically** [comment]
What does this exactly do?

**Comment by nts64** [comment]
evolves

Prints the total at the bottom as well

**Comment by Wolfsblvt** [comment]
I guess we can keep this PR open for people who want to use this.
But with the new UI we will add an evolution helper window of some kind that will show that information and do even more!

**Comment by nts64** [comment]
I mostly did this for my own use, good to know you'll be adding something more useful, closing this PR

**Pull request closed without merging**
