### PR TITLE
Saving the last used pattern and new Dialog for Rename

### PR DESCRIPTION
**Pull request by FernandoTBarros**
Saving the last used pattern in renaming operation on the config file
And creating a custom panel for the renaming operation to allow fast input copying values from a list.
(And in my pc the previous panel was bigger than the screen)

### CODE REVIEW

**Comment by FernandoTBarros** [comment]
#295

**Comment by Ljaysoft** [comment]
If you want to add that feature, you should start by using JavaFX instead of adding to PokemonTab.
it won't work in the current version but the sooner we work on getting it done, the better it is.
PokemonTab has become a monster, we need to move to a more modular structure ;)

**Comment by FernandoTBarros** [comment]
@Ljaysoft Yes, I totally agree! 
I've developed this functionality first in JavaFX (I have better knowledge in developing interfaces in JavaFX than Swing), but then I started to have problems calling the JavaFX Dialog inside the Swing thread, because of this I developed in Swing in the end.
I have this already developed in JavaFX in another branch in my local repository. 

How can I help you with this new layout?

**Comment by Ljaysoft** [comment]
Anything really lol, the faster it's done, the faster we go away from swing.

look at #324 to see where I'm at

**Comment by FernandoTBarros** [comment]
But is there any TODO list? Just to avoid implementing the same thing...

**Comment by Ljaysoft** [comment]
there are a list of issues with the tag v0.2.0, but at this point it's just being able to do the same thing than before. Make a branch and do a pull request and mention that its a work in progress, so you can document on what you plan on doing and I'll add the appropriate labels so it's easy to track.

Off the top of my head, we first need to implement the search field, then the window to confirm an operation with a list of pokémon selected and a summary of the operation (with variable descriptions).
this includes: rename, evolve, transfer and level. I think they should all have some custom window with similar design to be able to do the operations easily

**Comment by Ljaysoft** [comment]
The item tab hasn't been touched at all either.

**Comment by Ljaysoft** [comment]
needs merging

**Comment by Wolfsblvt** [comment]
Checked your PR now.
It is brilliant, working good!

And thanks that you took the time to fix all those code review issues :D

**Pull request merged**
