### PR TITLE
Show selected Pokémon in the title

### PR DESCRIPTION
**Pull request by westerlund**
Hi guys!

Thanks for an amazing tool.

I was missing a feature so I pulled the project and started hacking, I'm new to java.
What I implemented is a counter in the title bar when selecting Pokémon, for easier counting duplicates and so on. The count will only appear when two or more Pokémon are selected and will reset when deselected.

As I stated, I may have put this in the wrong place or implemented it incorrectly, but hey, it works :)

Best,
Simon

### CODE REVIEW

**Comment by Ljaysoft** [comment]
Small comment, it should say XX Pokémon Selected, instead of just XX Pokémon. (just to make things clear ;)

**Comment by westerlund** [comment]
@Ljaysoft makes sense, I pushed an update :)

**Comment by Wolfsblvt** [comment]
Does it replace the normal window title?
Can't check it right now, I am on my phone.

If not, I'll merge, was just a small change (:

**Comment by westerlund** [comment]
@Wolfsblvt it does, but only if two or more rows are selected! it gets reset once the section clears or one row is selected again. I thought it'd make sense to put it there since the app doesn't have a bottom bar.

**Comment by Wolfsblvt** [comment]
Yeah okay, that's fine then.
Until the new UI is ready at least, then we'll hopefully have a bottom bar.

I'll trust @Ljaysoft then who reviewed before. The new change is fine.
Will merge.

**Pull request merged**
