### PR TITLE
Added Stardust display, cleaned up, added level column

### PR DESCRIPTION
**Pull request by weblue**
- Added Stardust to program title.
- Readability in PokemonGoMainWindow code
- Cleaned up formatting and lambas
- Added levels column
- Rearranged columns
- Resized main window
- Added more exceptions

### CODE REVIEW

**Comment by wullxz** [comment]
See Issue #10

**Comment by ghost** [comment]
Hey there, I dig all the changes here, just resolve the conflicts, and submit the PR again, and I'd be happy to merge it :)

**Comment by weblue** [comment]
@Ljaysoft how can I keep my side up to date with the repo while fixing pull requests from an IDE?

**Comment by weblue** [comment]
Before, I was forking the repo, modifying my version, and sending a pull request

**Comment by weblue** [comment]
@Blossomforth I need write access to merge the pull request and resolve the conflicts

**Comment by weblue** [comment]
@Blossomforth nevermind, I did what I was doing before. Change log exploded a bit, but it's properly merged now

**Comment by ghost** [comment]
Awesome, thank you!

**Pull request merged**
